PREFIX metro: <https://grupo09.github.io/HandsOn/ontology#>
PREFIX data:  <https://grupo09.github.io/HandsOn/data/>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>

# --- CONSULTAS PARA VERIFICAR INFORMACIÓN RDF ---

# Número tripletas
SELECT (COUNT(*) AS ?totalTripletas)
WHERE {
  ?s ?p ?o .
}


# Número de elementos en clases
SELECT ?tipo (COUNT(?instancia) AS ?num)
WHERE {
  ?instancia a ?tipo .
}
GROUP BY ?tipo
ORDER BY DESC(?num)


# Verificar relaciones
SELECT ?linea ?estacion
WHERE {
  ?linea a metro:Linea ;
         metro:tieneEstacion ?estacion .
}

LIMIT 10


# Información estaciones
SELECT ?estacion ?alcaldia ?tipo ?linea
WHERE {
  ?estacion a metro:Estacion ;
             metro:estaEnAlcaldia ?alcaldia ;
             metro:tieneTipo ?tipo ;
             metro:deLinea ?linea .
}
LIMIT 10


# Información afluencias
SELECT ?medicion ?anio?afluencia ?estacion ?linea
WHERE {
  ?medicion a metro:MedicionAfluencia ;
            metro:anioMedicion ?anio ;
            metro:afluenciaMedicion ?afluencia ;
            metro:deEstacion ?estacion ;
            metro:deLinea ?linea .
}
LIMIT 10


# Verificar estaciones con mediciones
SELECT (COUNT(DISTINCT ?estacion) AS ?numEstacionesConAfluencia)
WHERE {
  ?m a metro:MedicionAfluencia ;
     metro:deEstacion ?estacion .
}